{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "0xhub.operator.fullname" . }}
  labels:
    {{- include "0xhub.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "0xhub.operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "0xhub.serviceAccountName" . }}
  namespace: {{ include "0xhub.namespace" . }}
{{- end }}

