apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub.fullname" . }}-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "hub.selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http

