{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hub.operator.fullname" . }}
  labels:
    {{- include "hub.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hub.operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hub.serviceAccountName" . }}
  namespace: {{ include "hub.namespace" . }}
{{- end }}

